### ISSUE TITLE
Difference between `rejectedByUser` and `canceledByUser`?

### ISSUE THREAD

**Issue by dcts** [radixdlt/wallet-sdk#89]
Can someone explain to me the difference between those 2 error types:
- `canceledByUser`
- `rejectedByUser`

Specifically I wonder: What user action leads to those errors? For example, when I press the "x" close button in the wallet, I get `rejectedByUser` error. What action do I need to do that leads to `canceledByUser` error?

Reference: https://github.com/radixdlt/wallet-sdk?tab=readme-ov-file#errors

**Comment by dawidsowardx** [comment]
![image](https://github.com/radixdlt/wallet-sdk/assets/119939994/eca64cb4-3c8d-40d9-9425-a768b0db992f)

Clicking "cancel" inside Connect Button **before** transaction reaches mobile wallet gives you `canceledByUser` error

**Comment by dcts** [comment]
Thanks a lot @dawidsowardx
